//! Every pattern in `data/gameobj-data.tsv` compiles under the `regex` crate.
//!
//! The file is a transcription of Lich's `data/gameobj-data.xml`, whose
//! patterns are Ruby regex. Ruby's dialect is a superset of this crate's: a
//! pattern can be a faithful copy of Lich and still not compile here. A column
//! recording "this one compiles" would go stale the next time the file is
//! regenerated; this test cannot.
//!
//! Regenerated by:
//!
//! ```text
//! python crates/cena-model/tools/convert_gameobj_data.py \
//!     C:/Gemstone/lich-5/data/gameobj-data.xml \
//!     crates/cena-model/data/gameobj-data.tsv
//! ```
//!
//! One pattern needed an edit. Lich's `jewelry` name is
//! `^(^(?!some).*\bplate$)$` -- a negative lookahead, which this crate does not
//! support. It is split into a `name` that matches and an `exclude` that vetoes,
//! the same shape `crit/match_index.rs` uses for the one lookahead in the crit
//! tables, and for the same reason recorded there: a second regex engine for a
//! single entry is complexity without a requirement to name it.

use regex::Regex;

const GAMEOBJ_TSV: &str = include_str!("../data/gameobj-data.tsv");

/// Header plus one row per `<name>`/`<noun>`/`<exclude>`/`<suffix>` element.
///
/// ```text
/// $ grep -cE '^    <(name|noun|exclude|suffix)>' \
///       /c/Gemstone/lich-5/data/gameobj-data.xml   -> 113
/// ```
const EXPECTED_ROWS: usize = 113;

/// Rows as `(line number, [kind, category, field, pattern])`.
///
/// A row with too few columns yields `None` rather than panicking, so the
/// malformed line is reported by the assertions below with its line number.
fn rows() -> impl Iterator<Item = (usize, Option<[&'static str; 4]>)> {
    GAMEOBJ_TSV
        .lines()
        .enumerate()
        .skip(1)
        .filter(|(_, line)| !line.is_empty())
        .map(|(i, line)| {
            let mut it = line.splitn(4, '\t');
            let cols = match (it.next(), it.next(), it.next(), it.next()) {
                (Some(k), Some(c), Some(f), Some(p)) => Some([k, c, f, p]),
                _ => None,
            };
            (i + 1, cols)
        })
}

#[test]
fn every_pattern_compiles() {
    let mut failures = Vec::new();
    let mut count = 0;

    for (line, cols) in rows() {
        count += 1;
        let Some([kind, category, field, pattern]) = cols else {
            failures.push(format!("  {line}: too few columns"));
            continue;
        };
        if let Err(e) = Regex::new(pattern) {
            let reason = e
                .to_string()
                .lines()
                .last()
                .unwrap_or_default()
                .trim()
                .to_owned();
            failures.push(format!("  {line}: {kind} {category}/{field}: {reason}"));
        }
    }

    assert_eq!(count, EXPECTED_ROWS, "row count changed; see EXPECTED_ROWS");
    assert!(
        failures.is_empty(),
        "{} of {count} patterns do not compile under the `regex` crate:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn columns_are_well_formed() {
    for (line, cols) in rows() {
        let Some([kind, category, field, pattern]) = cols else {
            panic!("line {line}: too few columns");
        };
        assert!(
            matches!(kind, "type" | "sellable"),
            "line {line}: unknown kind {kind:?}"
        );
        assert!(
            matches!(field, "name" | "noun" | "exclude" | "suffix"),
            "line {line}: unknown field {field:?}"
        );
        assert!(!category.is_empty(), "line {line}: empty category");
        assert!(!pattern.is_empty(), "line {line}: empty pattern");
    }
}

/// The `jewelry` split reproduces the lookahead it replaced.
///
/// Lich: `^(^(?!some).*\bplate$)$` -- anything ending in `plate` that does not
/// *start* with the four characters `some`. The negation has no word boundary,
/// so it rejects `somersault plate` as well as `some plate`; an `exclude` of
/// `^some\b` would not, which is why the folded alternative is `some.*`.
///
/// `jewelry` already had an `exclude` (tarnishable flatware -- `bent plate` is
/// not jewelry). The negation is folded into it as a leading alternative rather
/// than added as a second row, which would have silently replaced it.
#[test]
fn jewelry_split_matches_lichs_lookahead() {
    let get = |want: &str| {
        rows()
            .filter_map(|(_, cols)| cols)
            .find(|[_, category, field, _]| *category == "jewelry" && *field == want)
            .unwrap_or_else(|| panic!("no jewelry {want} row"))[3]
    };
    let name = Regex::new(get("name")).unwrap();
    let exclude = Regex::new(get("exclude")).unwrap();
    let matches = |s: &str| name.is_match(s) && !exclude.is_match(s);

    for s in ["gold plate", "plate", "a full plate", "SOME plate"] {
        assert!(matches(s), "{s:?} should match jewelry");
    }
    for s in [
        "some plate",
        "somersault plate",
        "somewhat plate",
        "some powdered plate",
        "someplate",
        "plated",
        "platesome",
        "",
        // Lich's own exclude: tarnishable flatware, not jewelry.
        "bent plate",
        "tarnished plate",
    ] {
        assert!(!matches(s), "{s:?} should not match jewelry");
    }
}
