# Extract eherbs' herb table (`EHerbs.known_herbs`) into
# crates/cena-model/data/herbs.tsv, whole.
#
#   ruby tools/extract_herbs.rb [path/to/eherbs.lic]
#
# The table is a Ruby literal, so it is evaluated rather than parsed by hand.
# Every key is kept, and a key this does not know fails the run: a new field
# in eherbs is a visible change here, never a silent drop (plan/36 Stage 1).

source = ARGV[0] || File.join(__dir__, '..', 'reference', 'scripts', 'scripts', 'eherbs.lic')
text = File.read(source, encoding: 'UTF-8')

start = text.index('def self.known_herbs') or abort("no known_herbs in #{source}")
open = text.index('[', start) or abort('no table literal')
# The literal ends at the first line that is only `    ]` after it.
close = text.index(/^\s{4}\]\s*$/, open) or abort('no end to the table literal')
literal = text[open..text.index(']', close)]

herbs = eval(literal) # rubocop:disable Security/Eval -- a literal from a reviewed file
abort('the table is not a list') unless herbs.is_a?(Array)

KEYS = %i[location name type short_name store_doses].freeze
herbs.each_with_index do |herb, i|
  unknown = herb.keys - KEYS
  abort("herb #{i} (#{herb[:name]}) has keys this does not know: #{unknown}") unless unknown.empty?
  missing = KEYS - herb.keys
  abort("herb #{i} (#{herb[:name]}) lacks #{missing}") unless missing.empty?
  herb[:location].each do |place|
    abort("herb #{i}: a location holds a tab or a bar: #{place}") if place =~ /[\t|]/
  end
end

commit = Dir.chdir(File.dirname(source)) { `git log -1 --format=%h%x20%cs -- #{File.basename(source)}`.strip }
version = text[/^\s*version:\s*(\S+)/, 1]
out = File.join(__dir__, '..', 'crates', 'cena-model', 'data', 'herbs.tsv')
File.open(out, 'w', newline: :lf) do |f|
  f.puts '# Generated by tools/extract_herbs.rb from eherbs.lic\'s known_herbs.'
  f.puts '# Do not hand-edit: re-run the tool.'
  f.puts "# source\treference/scripts/scripts/eherbs.lic"
  f.puts "# source-commit\t#{commit.empty? ? 'unknown' : commit}"
  f.puts "# source-version\t#{version}"
  f.puts "# herbs\t#{herbs.length}"
  f.puts "name\tshort_name\ttype\tstore_doses\tlocations"
  herbs.each do |herb|
    f.puts [herb[:name], herb[:short_name], herb[:type], herb[:store_doses], herb[:location].join('|')].join("\t")
  end
end
puts "#{herbs.length} herbs -> #{out}"
