# Extract what the spell table (crates/cena-model/data/spells.tsv) did not
# keep from Lich's data/effect-list.xml, into
# crates/cena-model/data/spell_extras.tsv, joined to the table by number
# (plan/37 Stage 1).
#
#   ruby tools/extract_spell_extras.rb [path/to/effect-list.xml]
#
# Kept whole: every attribute of <spell>, of each <duration> in order, and of
# each <cost> with its text as written, and the <cast-proc>. An attribute or
# a child element this does not know fails the run, so a new field in the
# file is a visible change here, never a silent drop.

require 'rexml/document'

source = ARGV[0] || 'C:/Gemstone/lich-5/data/effect-list.xml'
doc = REXML::Document.new(File.read(source, encoding: 'UTF-8'))

SPELL_ATTRS = %w[availability channel incant name number stance type].freeze
DURATION_ATTRS = %w[cast-type span multicastable max persist-on-death real-time].freeze
COST_ATTRS = %w[type fixme].freeze
CHILDREN = %w[duration cost bonus message cast-proc cooldown].freeze

UNIT = "\u001f" # between the parts of one value
REC = "\u001e"  # between values in one column

def clean(text)
  text.to_s.gsub(/[\t\r\n]+/, ' ').strip
end

def check(element, known, what)
  unknown = element.attributes.keys - known
  abort("#{what} has attributes this does not know: #{unknown}") unless unknown.empty?
end

rows = []
seen = {}
doc.elements.each('list/spell') do |spell|
  check(spell, SPELL_ATTRS, "spell #{spell.attributes['number']}")
  number = spell.attributes['number']
  # The first of a duplicated number wins, as the spell table's rule does.
  next if seen[number]

  seen[number] = true
  spell.elements.each do |child|
    abort("spell #{number} has a <#{child.name}> this does not know") unless CHILDREN.include?(child.name)
  end
  durations = spell.get_elements('duration').map do |d|
    check(d, DURATION_ATTRS, "spell #{number}'s duration")
    DURATION_ATTRS.map { |a| d.attributes[a].to_s }.join(UNIT)
  end
  costs = spell.get_elements('cost').map do |c|
    check(c, COST_ATTRS, "spell #{number}'s cost")
    [c.attributes['type'].to_s, clean(c.text), c.attributes['fixme'].to_s].join(UNIT)
  end
  proc_text = spell.get_elements('cast-proc').map { |p| clean(p.text) }.join(REC)
  # Every message, with its type: the table keeps one per type, and 98 were
  # overwritten (inventory/12 §1.1).
  messages = spell.get_elements('message').map do |m|
    check(m, %w[type], "spell #{number}'s message")
    [m.attributes['type'].to_s, clean(m.text)].join(UNIT)
  end
  rows << [
    number,
    spell.attributes['incant'].to_s,
    spell.attributes['stance'].to_s,
    spell.attributes['channel'].to_s,
    durations.join(REC),
    costs.join(REC),
    proc_text,
    messages.join(REC)
  ]
end

abort('a value holds a tab') if rows.flatten.any? { |v| v.include?("\t") }

out = File.join(__dir__, '..', 'crates', 'cena-model', 'data', 'spell_extras.tsv')
mtime = File.mtime(source).strftime('%Y-%m-%d %H:%M:%S')
File.open(out, 'w', newline: :lf) do |f|
  f.puts '# Generated by tools/extract_spell_extras.rb from Lich\'s data/effect-list.xml.'
  f.puts '# Do not hand-edit: re-run the tool.'
  f.puts "# source\t#{source}"
  f.puts "# source-mtime\t#{mtime}"
  f.puts "# spells\t#{rows.length}"
  f.puts "# duration-parts\t#{DURATION_ATTRS.join(' ')}"
  f.puts "# cost-parts\ttype text fixme"
  f.puts "# messages\t#{rows.sum { |r| r[7].empty? ? 0 : r[7].split(REC).length }}"
  f.puts "number\tincant\tstance\tchannel\tdurations\tcosts\tcast_proc\tmessages"
  rows.each { |row| f.puts row.join("\t") }
end
puts "#{rows.length} spells -> #{out}"
